# Generated by Django 4.0.6 on 2023-11-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semanticImageSearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='semanticimagesearch',
            name='image',
        ),
        migrations.RemoveField(
            model_name='semanticimagesearch',
            name='phrase',
        ),
        migrations.AddField(
            model_name='semanticimagesearch',
            name='query',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semanticimagesearch',
            name='result',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='semanticimagesearch',
            name='images',
            field=models.ManyToManyField(to='semanticImageSearch.image'),
        ),
    ]
