# Generated by Django 4.0.6 on 2023-11-18 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_semanticimagesearch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SemanticImageSearch',
        ),
    ]
