# Generated by Django 4.0.6 on 2023-11-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0005_alter_semanticimagesearch_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='semanticimagesearch',
            name='image_features',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
