# Generated by Django 4.0.6 on 2023-11-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0006_semanticimagesearch_image_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semanticimagesearch',
            name='image_features',
            field=models.TextField(blank=True),
        ),
    ]
