# Generated by Django 4.0.6 on 2023-11-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0007_alter_semanticimagesearch_image_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semanticimagesearch',
            name='image_features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
