# Generated by Django 4.0.6 on 2023-11-27 11:16

import classifier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0010_alter_classifier_image_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifier',
            name='image',
            field=models.ImageField(upload_to=classifier.models.get_image_path),
        ),
    ]
