# Generated by Django 4.0.6 on 2023-12-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0014_semanticimagesearch_result_full_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('phrase', models.TextField()),
            ],
        ),
    ]
