# Generated by Django 4.0.6 on 2023-12-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uploaded_photos',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs', null=True),
        ),
    ]
